name: terraform-plan

on:
  pull_request:

permissions:
  id-token: write
  contents: read

jobs:
  plan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [dev, qa, prod]

    defaults:
      run:
        working-directory: env/${{ matrix.env }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Terraform fmt (repo-wide)
        run: terraform fmt -check -recursive
        working-directory: ${{ github.workspace }}

      - name: Terraform init
        run: terraform init -reconfigure

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan
        run: terraform plan -var-file="${{ matrix.env }}.tfvars" -no-color
